version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/main"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/main"
    schedule:
      interval: "daily"